### ISSUE TITLE
[4] English US language pack issue

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/core-translations#35]
### Steps to reproduce the issue

install Joomla 4 and use English USA as the default language 

create a new article on frontend or backend 

note the tab

### Actual result

<img width="1189" alt="Screenshot 2021-08-17 at 22 47 35" src="https://user-images.githubusercontent.com/400092/129805121-c06e012b-5116-42fc-83bf-6851cd91c762.png">

**Comment by zero-24** [comment]
The issue has been moved as requested

**Comment by PhilETaylor** [comment]
<img width="911" alt="Screenshot 2021-08-22 at 12 26 58" src="https://user-images.githubusercontent.com/400092/130353350-cd462c7d-3f62-4163-83ed-e843b355ed14.png">

**Comment by particthistle** [comment]
Awaiting Crowdin build to complete in order to prepare 4.0.0.12 language pack for en-US.

All identified strings have been corrected.
Additional strings in the files that relate to the corrections have also been checked (Crowdin Translation Memory on import has caused most of them, but additionally some strings had been changed between en-US being on crowdin.com and moving to joomla.crowdin.com.

**Comment by particthistle** [comment]
Language pack finally released: en-US 4.0.1.2 resolves all of the issues identified above + additional ones triggered for 4.0.1 release.
